from airflow import DAG
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
import pendulum
from datetime import datetime, timedelta

# ==========================================
# 1. 기본 설정 (Default Arguments)
# ==========================================
default_args = {
    'owner': 'woals24952495', # <--- Owner 변경
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=1),
}

# ==========================================
# 2. DAG 정의
# ==========================================
dag = DAG(
    'woals24952495_seoul_subway_delay_calculator', # <--- DAG ID 변경 (유니크해야 함)
    default_args=default_args,
    description='10분마다 Supabase 테이블 갱신 및 지연시간 계산',
    schedule='*/10 * * * *',  # [변경] 10분마다 실행 (테스트용)
    start_date=pendulum.datetime(2023, 1, 1, tz='Asia/Seoul'),   # [변경] KST 설정
    catchup=False,                     # 과거 밀린 작업은 실행 안 함
    tags=['subway', 'supabase', 'woals24952495'], # <--- Tag 추가
)

# ==========================================
# 3. 실행할 SQL 쿼리 정의
# ==========================================

# Task 1: 데이터 가공 (View 생성) - 실시간 로그를 요약된 형태로 변환
sql_create_view = """
    CREATE OR REPLACE VIEW "test1_realtime_summary" AS
    SELECT
        DATE(last_rec_time) as created_date,
        line_name,
        station_name,
        up_down,
        regexp_replace(train_code, '[^0-9]', '', 'g') as train_code_num,
        is_express,
        dest_station_name,
        -- 도착(0,1) 중 가장 빠른 시간
        MIN(last_rec_time) FILTER (WHERE train_status IN (0, 1)) as actual_arrival,
        -- 출발(2) 중 가장 빠른 시간
        MIN(last_rec_time) FILTER (WHERE train_status = 2) as actual_departure
    FROM "final_realtime_subway"
    GROUP BY 
        DATE(last_rec_time),
        line_name,
        station_name,
        up_down,
        regexp_replace(train_code, '[^0-9]', '', 'g'),
        is_express,
        dest_station_name;
"""

# Task 2: 가공된 View에서 최근 1시간 데이터 추출 (table_1hour)
sql_refresh_1hour = """
    DROP TABLE IF EXISTS "table_1hour";

    CREATE TABLE "table_1hour" AS
    SELECT *
    FROM "test1_realtime_summary"
    -- actual_arrival이 있거나 actual_departure가 있는 데이터 중 최근 것
    WHERE COALESCE(actual_arrival, actual_departure) >= (NOW() - INTERVAL '1 hour 30 minutes');

    ALTER TABLE "table_1hour" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
"""

# Task 3: 지연 시간 계산 (table_redash_test)
sql_calc_delay = """
    DROP TABLE IF EXISTS "table_redash_test";

    CREATE TABLE "table_redash_test" AS
    SELECT 
        RT.created_date,
        RT.line_name,
        RT.station_name,
        RT.up_down,
        RT.train_code_num,
        RT.is_express,
        RT.dest_station_name,
        
        -- [시간 확인용]
        RT.actual_arrival AS utc_arrival, 
        (RT.actual_arrival + interval '9 hours') AS kst_arrival, 
        SC.time_arrive AS scheduled_arrival_text,
        
        -- [지연 시간 계산]
        CASE 
            WHEN RT.actual_arrival IS NOT NULL THEN 
                ((RT.actual_arrival + interval '9 hours')::time - SC.time_arrive::time)
            ELSE 
               NULL
        END AS delay_duration

    FROM "table_1hour" AS RT
    JOIN "table_1-9_line" AS SC
        ON RT.line_name = SC.line_name
        AND RT.station_name = SC.station_name
        AND RT.up_down = SC.up_down 
        AND RT.is_express = SC.is_express 
        -- 열차번호 숫자 매칭
        AND CAST(RT.train_code_num AS INTEGER) 
          = CAST(REGEXP_REPLACE(SC.train_code::text, '\D', '', 'g') AS INTEGER);

    -- [Task B] ID 중복 방지
    ALTER TABLE "table_redash_test" DROP COLUMN IF EXISTS id;
    ALTER TABLE "table_redash_test" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
"""

# ==========================================
# 4. Task 정의 (SQLExecuteQueryOperator 사용)
# ==========================================

t1_create_view = SQLExecuteQueryOperator(
    task_id='create_view_summary',
    conn_id='jaemin1077_supabase_conn',
    sql=sql_create_view,
    dag=dag,
)

t2_refresh_1hour = SQLExecuteQueryOperator(
    task_id='refresh_table_1hour',
    conn_id='jaemin1077_supabase_conn', 
    sql=sql_refresh_1hour,
    dag=dag,
)

t3_calc_delay = SQLExecuteQueryOperator(
    task_id='refresh_table_redash_test',
    conn_id='jaemin1077_supabase_conn',
    sql=sql_calc_delay,
    dag=dag,
)

# ==========================================
# 5. 실행 순서 설정
# ==========================================
# 뷰 생성/갱신 -> 1시간 데이터 추출 -> 지연 계산
t1_create_view >> t2_refresh_1hour >> t3_calc_delay