from airflow import DAG
from airflow.providers.postgres.operators.postgres import PostgresOperator
from datetime import datetime, timedelta

# ==========================================
# 1. 기본 설정 (Default Arguments)
# ==========================================
default_args = {
    'owner': 'woals24952495', # <--- Owner 변경
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=1),
}

# ==========================================
# 2. DAG 정의
# ==========================================
dag = DAG(
    'woals24952495_seoul_subway_delay_calculator', # <--- DAG ID 변경 (유니크해야 함)
    default_args=default_args,
    description='10분마다 Supabase 테이블 갱신 및 지연시간 계산',
    schedule_interval='*/10 * * * *',  # [중요] 10분마다 실행 (Cron 표현식)
    start_date=datetime(2023, 1, 1),   # 시작일 (과거로 설정해두면 켜자마자 실행됨)
    catchup=False,                     # 과거 밀린 작업은 실행 안 함
    tags=['subway', 'supabase', 'woals24952495'], # <--- Tag 추가
)

# ==========================================
# 3. 실행할 SQL 쿼리 정의
# ==========================================

# Task 1: 최근 1시간 데이터 추출 (table_1hour)
sql_refresh_1hour = """
    DROP TABLE IF EXISTS "table_1hour";


    CREATE TABLE "table_1hour" AS
    SELECT *
    FROM "final_realtime_subway"
    WHERE last_rec_time >= (NOW() - INTERVAL '1 hour');

    -- [Task B] ID 중복 방지: 기존 id가 있다면 삭제 후 새로 생성 (혹은 없으면 무시)
    ALTER TABLE "table_1hour" DROP COLUMN IF EXISTS id;
    ALTER TABLE "table_1hour" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
"""

# Task 2: 지연 시간 계산 (table_redash_test) - KST 변환 포함
sql_calc_delay = """
    DROP TABLE IF EXISTS "table_redash_test";

    CREATE TABLE "table_redash_test" AS
    SELECT 
        RT.last_rec_time AS created_date,
        RT.line_name,
        RT.station_name,
        RT.up_down,
        RT.train_code AS train_code_num,
        RT.is_express,
        RT.dest_station_name,
        
        -- [시간 확인용]
        RT.last_rec_time AS utc_arrival, 
        (RT.last_rec_time + interval '9 hours') AS kst_arrival, 
        SC.time_arrive AS scheduled_arrival_text,
        
        -- [지연 시간 계산: (UTC+9h) - KST시간표]
        CASE 
            WHEN RT.last_rec_time IS NOT NULL THEN 
                ((RT.last_rec_time + interval '9 hours')::time - SC.time_arrive::time)
            ELSE 
               NULL
        END AS delay_duration

    FROM "final_realtime_subway" AS RT
    JOIN "table_1-9_line" AS SC
        ON RT.line_name = SC.line_name
        AND RT.station_name = SC.station_name
        AND RT.up_down = SC.up_down 
        AND RT.is_express = SC.is_express 
        -- 열차번호 숫자 매칭
        AND CAST(REGEXP_REPLACE(RT.train_code::text, '\D', '', 'g') AS INTEGER) 
          = CAST(REGEXP_REPLACE(SC.train_code::text, '\D', '', 'g') AS INTEGER);

    -- [Task B] ID 중복 방지
    ALTER TABLE "table_redash_test" DROP COLUMN IF EXISTS id;
    ALTER TABLE "table_redash_test" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
"""

# ==========================================
# 4. Task 정의 (PostgresOperator 사용)
# ==========================================

# [중요] postgres_conn_id에는 Airflow UI에서 설정한 Connection ID를 입력해야 합니다.
# 여기서는 'supabase_conn'이라고 가정했습니다.
t1_refresh_1hour = PostgresOperator(
    task_id='refresh_table_1hour',
    postgres_conn_id='jaemin1077_supabase_conn', 
    sql=sql_refresh_1hour,
    dag=dag,
)

t2_calc_delay = PostgresOperator(
    task_id='refresh_table_redash_test',
    postgres_conn_id='jaemin1077_supabase_conn',
    sql=sql_calc_delay,
    dag=dag,
)

# ==========================================
# 5. 실행 순서 설정
# ==========================================
# 1시간 데이터 먼저 만들고 -> 그 다음 지연 시간 계산 (순차 실행)
t1_refresh_1hour >> t2_calc_delay