-- Create table for Seoul Subway Realtime Positions
CREATE TABLE public.realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(100),
    line_name VARCHAR(100),
    station_id VARCHAR(100),
    station_name VARCHAR(100),
    train_number VARCHAR(100),
    last_rec_date VARCHAR(100),
    last_rec_time TIMESTAMP WITH TIME ZONE,
    direction_type INTEGER, -- 0: Up/Inner, 1: Down/Outer
    dest_station_id VARCHAR(100),
    dest_station_name VARCHAR(100),
    train_status INTEGER, -- 0:Enter, 1:Arrive, 2:Depart, 3:Pre-depart
    is_express INTEGER, -- 1:Express, 0:No, 7:Special
    is_last_train BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) is recommended on Supabase public tables
ALTER TABLE public.realtime_subway_positions ENABLE ROW LEVEL SECURITY;

-- Creating a policy to allow public read access (optional, adjust based on needs)
CREATE POLICY "Allow public read access"
ON public.realtime_subway_positions
FOR SELECT USING (true);

-- Policy to allow authenticated insert (service role)
CREATE POLICY "Allow service role insert"
ON public.realtime_subway_positions
FOR INSERT WITH CHECK (true);
